### ISSUE TITLE
math range error - faders jumps up and down 

### ISSUE THREAD

**Issue by koteckyy** [praashie/fl-novation-impulse#3]
faders not working as faders but as buttons. I can get value 0 or 127 only. Version 5.0.
Version 5.1 not working in my case at all (do not see any move in debug log)

I would love to have it fixed bcs is working just excellent <3

  File "C:\Users\kotda\Documents\Image-Line\FL Studio\Settings\Hardware\fl-novation-impulse-0.5.0\flatmate\mixer.py", line 33, in getValueString
  File "C:\Program Files\Image-Line\Shared\Python\Lib\utils.py", line 210, in VolTodB
OverflowError: math range error
Traceback (most recent call last):
  File "C:\Users\kotda\Documents\Image-Line\FL Studio\Settings\Hardware\fl-novation-impulse-0.5.0\flatmate\chain.py", line 46, in __call__
  File "C:\Users\kotda\Documents\Image-Line\FL Studio\Settings\Hardware\fl-novation-impulse-0.5.0\flatmate\control.py", line 69, in OnControlChange
  File "<string>", line 296, in onFader
  File "<string>", line 394, in displayEventFeedback
  File "C:\Users\kotda\Documents\Image-Line\FL Studio\Settings\Hardware\fl-novation-impulse-0.5.0\flatmate\mixer.py", line 33, in getValueString
  File "C:\Program Files\Image-Line\Shared\Python\Lib\utils.py", line 210, in VolTodB
OverflowError: math range error

**Comment by koteckyy** [comment]
I checked debug log and its jumping up to max when value of fader is changing from b0 00 00 to b0 00 01. after whole scale up to 100 giving nothing.

**Comment by praashie** [comment]
Are you running on Beta version of FL?

**Comment by koteckyy** [comment]
Hi. I am running this on 20.7. I checked it on 20.8 and it working perfectly. There is any chance to run it on 20.7? I love this script but I need to work on 20.7...

**Comment by koteckyy** [comment]
anything?
